---

- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"

- name: Provisioning the web server
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - create-www-data-user
  # - ubuntu-apt
    - certbot
    - nginx
    - geerlingguy.nodejs
    - geerlingguy.postgresql
